version: '3.8'

services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: woolfr
      MYSQL_DATABASE: woolfr
      MYSQL_USER: root
      MYSQL_PASSWORD: woolfr
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: woolfr
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: